### ISSUE TITLE
post to twitter and save to dynamodb

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#16]
KR: post to twitterand save to dynamodb
- use twitter library
- add a post API
  - create a API project: https://www.npmjs.com/package/twitter
  - create post API
  - save post data to DynamoDB 

```
var client = new Twitter({
  consumer_key: 'xGwoSRAdx8FQoc2WKYVGUsFtJ',
  consumer_secret: 'Ly0Bl8om7HGPToPjNoPp8KAlzhpmQiUTFJtmB9HW0tCAXWXhIv',
  bearer_token: 'AAAAAAAAAAAAAAAAAAAAAD6zewEAAAAAY2m5dOB9nJGp3I%2FXqOZYvAqd%2Fpw%3DYwKOHI3nLvXxdxNtD0OZgw1bWGGanqvzgIw5pQ96iGOgylsh8z'
});
```

![image](https://user-images.githubusercontent.com/11794032/179392419-e7560560-0246-45ff-8e0d-2fa9072bf5a0.png)

**Comment by hanchenglin** [comment]
It will be finished 7/26

**Comment by minhtuan412** [comment]
https://github.com/58web3/drawww/pull/20

**Comment by hanchenglin** [comment]
https://github.com/58web3/drawww/pull/22
