### ISSUE TITLE
Add posts GET  API and display posts in HOME

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#17]
KR: Add posts GET  API and display posts in HOME

- Add get all posts API
- Display list in HOME PAGE

![image](https://user-images.githubusercontent.com/11794032/179392737-a204c823-b2f0-4487-9a2a-c1dad41e2cac.png)

**Comment by hanchenglin** [comment]
It will be finished 7/26

**Comment by minhtuan412** [comment]
https://github.com/58web3/drawww/pull/21
I updated lastest code in https://github.com/58web3/drawww/pull/21

**Comment by hanchenglin** [comment]
@minhtuan412 The image URL is incorrect.

**Comment by hanchenglin** [comment]
https://github.com/58web3/drawww/pull/21
