### ISSUE TITLE
Call /v1/twitter/create occurs name too long error

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#25]
## Problem
Upload an image,  when call /v1/twitter/create occurs name too long error

## Evidence
![image](https://user-images.githubusercontent.com/11794032/182024411-8715e42f-c0a9-4aab-b9e7-2a88387a9429.png)

## Bug fix
Do not upload image content to twitter(api\src\twitter.js postTwitter  method)! Please use IPFS url from DynamoDB.

```
    const ipfsURL= from DynamoDB
    const postContent = 'NFT xx '+ ipfsURL;
    const params = { status: postContent };
    twitter.post('statuses/update', params,  (error, tweet, response) => {
```

**Comment by minhtuan412** [comment]
Link PR: https://github.com/58web3/drawww/pull/30
