### ISSUE TITLE
Change 「投稿する」button →「NFTをMintする」button  in detail page!

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#26]
## Problem
- Current detail button is not right!
- No mint function when click button

### Current
![image](https://user-images.githubusercontent.com/11794032/182025254-480e581c-5db9-4111-a7a6-58297de3f6c0.png)

### Figma
![image](https://user-images.githubusercontent.com/11794032/182025122-efa8d5a2-e75a-4b66-997c-fa26df72a40f.png)

## Bug fix
- Change button name「投稿する」→「NFTをMintする」
- When click 「NFTをMintする」button, mint a NFT using current post detail info to create NFT metadata. such as: name, url(IPFS)

**Comment by minhtuan412** [comment]
https://github.com/58web3/drawww/pull/32

**Comment by hanchenglin** [comment]
@minhtuan412  
smaple source:
1. connect to metamask
[connect-metamask_vue.txt](https://github.com/58web3/drawww/files/9238635/connect-metamask_vue.txt)

2. mint from vue:   async mint (blockchain: string) { 
[mint.vue.txt](https://github.com/58web3/drawww/files/9238643/mint.vue.txt)

3. web3service
[web3Service.ts.txt](https://github.com/58web3/drawww/files/9238651/web3Service.ts.txt)


4. EthereumService:   async mint (accountAddress:string, urlMetaData:string): Promise<any> {

[EthereumService.ts.txt](https://github.com/58web3/drawww/files/9238657/EthereumService.ts.txt)


Step1: create a web3 object

Step2: create a contract object

```
const nftErc721 = new web3.eth.Contract(
      abi,
      NFT_USE_ERC721_ADDRESS_CONTRACT
    )
```

Step3: Call mint method
```
await nftErc721.methods
        .mintSingleNFT(urlMetaData)
        .send({
          from: accountAddress,
          gasLimit: Number(GAS_LIMIT)
        })
        .on('transactionHash', function () {})
        .on('receipt', function (receipt:any) {
          transactionSuccess = receipt
        //   console.log('this is recept ether', receipt)
        })
```

**Comment by tuannm412** [comment]
> @minhtuan412 smaple source:
> 
> 1. connect to metamask
>    [connect-metamask_vue.txt](https://github.com/58web3/drawww/files/9238635/connect-metamask_vue.txt)
> 2. mint from vue:   async mint (blockchain: string) {
>    [mint.vue.txt](https://github.com/58web3/drawww/files/9238643/mint.vue.txt)
> 3. web3service
>    [web3Service.ts.txt](https://github.com/58web3/drawww/files/9238651/web3Service.ts.txt)
> 4. EthereumService:   async mint (accountAddress:string, urlMetaData:string): Promise {
> 
> [EthereumService.ts.txt](https://github.com/58web3/drawww/files/9238657/EthereumService.ts.txt)
> 
> Step1: create a web3 object
> 
> Step2: create a contract object
> 
> ```
> const nftErc721 = new web3.eth.Contract(
>       abi,
>       NFT_USE_ERC721_ADDRESS_CONTRACT
>     )
> ```
> 
> Step3: Call mint method
> 
> ```
> await nftErc721.methods
>         .mintSingleNFT(urlMetaData)
>         .send({
>           from: accountAddress,
>           gasLimit: Number(GAS_LIMIT)
>         })
>         .on('transactionHash', function () {})
>         .on('receipt', function (receipt:any) {
>           transactionSuccess = receipt
>         //   console.log('this is recept ether', receipt)
>         })
> ```

Thanks so much.
I will follow it

**Comment by tuannm412** [comment]
click connect metamask button, it will open metamask extension on browser
![image](https://user-images.githubusercontent.com/107101404/182508936-e98f88a5-bc41-4ec6-b0aa-05078cde217b.png)

**Comment by tuannm412** [comment]
click mint NFT button, it will send metadata and get new address
but I use localhost so I don't have ETH
I will run test with ganache
![image](https://user-images.githubusercontent.com/107101404/182509311-27ffd0f9-13f4-4640-9c79-1e1e77ffa9d3.png)

**Comment by hanchenglin** [comment]
@minhtuan412 please import your deploy account into metamask!
![image](https://user-images.githubusercontent.com/11794032/182567158-b969f6a2-7ed2-4b3f-8372-eb9f8e6b0aa9.png)

![image](https://user-images.githubusercontent.com/11794032/182567284-d6b2b9fe-0a61-4ac3-952c-ce833a7d45d0.png)

**Comment by hanchenglin** [comment]
@minhtuan412  I try on bug/test_for_#26. I left message on slack channel!

**Comment by minhtuan412** [comment]
![image](https://user-images.githubusercontent.com/99988937/182748549-a993bede-f84d-401a-9764-6d105bfc2773.png)
![image](https://user-images.githubusercontent.com/99988937/182748618-d3231e95-4e81-422e-917b-0a441ec155b8.png)
![image](https://user-images.githubusercontent.com/99988937/182748686-c29082df-5d86-4a04-8fa2-9c75c04e418f.png)

**Comment by hanchenglin** [comment]
Will run app in localhost
