### ISSUE TITLE
marketplace page still using a sample data, make page as a dynamic page

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#27]
## Problem 
marketplace page still using a sample data, make page as a dynamic page

## Evidence
![image](https://user-images.githubusercontent.com/11794032/182025422-de093fc6-f26f-480f-9624-d20f889a76fc.png)

## Bug fix
- Display NFT's image using NTF's image URL. ※Green area
- Display NFT token information ※Red area
- Save contract info and market url to DynamoDB

**Comment by minhtuan412** [comment]
https://github.com/58web3/drawww/pull/33
