### ISSUE TITLE
MarketCompleted Page is still using sample data, make page as a dyanmic page

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#28]
## Problem
MarketCompleted Page is still using sample data, make page as a dyanmic page

### Current
![image](https://user-images.githubusercontent.com/11794032/182025566-f27c6b3e-8a8e-4633-825f-fb720bcacd21.png)

### Figma
![image](https://user-images.githubusercontent.com/11794032/182025581-a300eda6-5e82-44e5-896d-2232a053e8f1.png)

## Bug fix
- Display page using NFT meta data

**Comment by minhtuan412** [comment]
https://github.com/58web3/drawww/pull/33
