### ISSUE TITLE
DAO page is still using a sample data, make page as a dynamic page

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#29]
## Problem 
DAO page is still using a sample data, make page as a dynamic page

frontend\components\dao\DaoPage.vue

### Current
![image](https://user-images.githubusercontent.com/11794032/182025715-8c433c44-3a55-4d65-9bde-aaf520985de0.png)

### Figma
![image](https://user-images.githubusercontent.com/11794032/182025775-2b2e7b16-fed7-4a3e-8202-6727b3b368b9.png)

## Bugfix
- Create a get API  ※We should consider the details
-  Display API in  DAO page

**Comment by minhtuan412** [comment]
https://github.com/58web3/drawww/pull/33

**Comment by hanchenglin** [comment]
@minhtuan412 Please create a new branch for each issue! This is rule!

When no data, please display a message, not a blank page!

![Image](https://user-images.githubusercontent.com/11794032/183466353-aff5a1cd-1e18-44c1-9bd4-38a3b6594489.png)

**Comment by hanchenglin** [comment]
@minhtuan412 Please attach evidence.
- many data
- no data

**Comment by minhtuan412** [comment]
No data
![image](https://user-images.githubusercontent.com/99988937/184243549-5808d837-0fa7-4907-87c1-3e245433abbd.png)

Many data
![image](https://user-images.githubusercontent.com/99988937/184244581-f8646612-2d49-4cad-8a52-75ed8325e5b9.png)
