### ISSUE TITLE
[閲覧する] button can not work in /post/post-completed page

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#31]
## Problem
[閲覧する] button can not work in /post/post-completed page. When i click button, no action

## Evidence
![image](https://user-images.githubusercontent.com/11794032/182164337-ae692d66-b071-458f-bd6d-71c7b245385e.png)

## Bugfix
when click button, can direct to https://twitter.com/home

**Comment by minhtuan412** [comment]
https://github.com/58web3/drawww/pull/33

**Comment by hanchenglin** [comment]
@minhtuan412 
- Please display text in red area
- Do not need display file name
- Display image below text area

**Comment by hanchenglin** [comment]
@minhtuan412  Please create a new branch for each issue in future! This is rule!
