### ISSUE TITLE
multilingual support

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#37]
## Problem
Label is hard-code

## Evidence
For example:

![Image](https://user-images.githubusercontent.com/11794032/183279966-b0fa20ee-429d-40f7-a703-70495fe46890.png)

## Bugfix
- add i18n json file
- modify all page for can support English and Japanese!

**Comment by minhtuan412** [comment]
https://github.com/58web3/drawww/pull/46

**Comment by minhtuan412** [comment]
![image](https://user-images.githubusercontent.com/99988937/184232343-baff7e61-d2f8-477f-a63b-d8453e7c42ed.png)
![image](https://user-images.githubusercontent.com/99988937/184232838-7780d649-edbc-479b-8ed9-a34a96abd50e.png)
