### ISSUE TITLE
change detail page url like /post/{post_id}

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#39]
## Problem
Current detal page url is `/detail`

## Evidence

![Image](https://user-images.githubusercontent.com/11794032/183280223-169f45ea-0708-4adb-a356-a202cd845aef.png)

## Bugfix
change detail page url like /post/{post_id}

**Comment by minhtuan412** [comment]
![image](https://user-images.githubusercontent.com/99988937/184249292-38d5c79a-9165-4218-bb4c-4dbc7cb0f16e.png)
PR: https://github.com/58web3/drawww/pull/48
