### ISSUE TITLE
Display description in detail page

### ISSUE THREAD

**Issue by hanchenglin** [58web3/drawww#45]
## Problem
description  do not display in detail page

## Bugfix
Display description in Red area!

![image](https://user-images.githubusercontent.com/11794032/184056235-35f53016-2930-4054-97bd-2ae9b2b66ebe.png)

**Comment by minhtuan412** [comment]
![image](https://user-images.githubusercontent.com/99988937/184251887-0a1a7394-1f05-4131-bfb3-bcf75ff7c32b.png)
PR: https://github.com/58web3/drawww/pull/49
